development:
  key: "0e5053bf33ac70fd2af0fb3d9b0552f7"
  secret: "7bda482387444871"
  url: "http://localhost:3000"
  callback: "http://localhost:3000/syncs/douban_callback"

production:
  key: "0e5053bf33ac70fd2af0fb3d9b0552f7"
  secret: "7bda482387444871"
  url: "http://www.1dooo.com"
  callback: "http://www.1dooo.com/syncs/douban_callback"
