test:
  key: "2054816412"
  secret: "75487227b4ada206214904bb7ecc2ae1"
  url: "http://localhost:3000"
  callback: "http://localhost:3000/syncs/sina_callback"

development:
  key: "2054816412"
  secret: "75487227b4ada206214904bb7ecc2ae1"
  url: "http://localhost:3000"
  callback: "http://localhost:3000/syncs/sina_callback"

production:
  key: "2054816412"
  secret: "75487227b4ada206214904bb7ecc2ae1"
  url: "http://www.dface.cn"
  callback: "http://www.dface.cn/syncs/sina_callback"
