development:
  key: "cu7N5Tp8BtUZPTEQb5FH"
  secret: "VeqX^LSr-hNBVVnOnSCa22^*C6($YTgD-4NFE*Vb"
  url: "http://localhost:3000"
  callback: "http://localhost:3000/syncs/sohu_callback"

production:
  key: "cu7N5Tp8BtUZPTEQb5FH"
  secret: "VeqX^LSr-hNBVVnOnSCa22^*C6($YTgD-4NFE*Vb"
  url: "http://www.1dooo.com"
  callback: "http://www.1dooo.com/syncs/sohu_callback"
