test:
  sessions:
    default:
      database: dface_test
      hosts:
        - 10.135.44.107:27017
        - 10.135.44.204:27017
      options:
        safe: true
        consistency: :eventual
    dooo:
      database: dface
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :eventual
