test:
  sessions:
    default:
      database: dface_test2
      hosts:
        - 10.241.42.47:27017
      options:
        safe: true
        consistency: :eventual
    dooo:
      database: dface_test2
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :eventual
