development:
  sessions:
    default:
      database: dface
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :eventual
      
    # allow_dynamic_fields: true
    # protect_sensitive_fields: true
    # raise_not_found_error: true
    # scope_overwrite_exception: false
    # skip_version_check: false
    # use_activesupport_time_zone: true
    # use_utc: false
production:
  sessions:
    default:
      database: dface
      hosts:
        - 10.135.44.107:27017
        - 10.135.44.204:27017
        - 10.241.42.47:27017
        - 10.132.36.138:27017
      options:
        safe: true
        consistency: :eventual

test:
  sessions:
    default:
      database: dface_test
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :strong

test2:
  sessions:
    default:
      database: dface
      hosts:
        - 10.132.36.138:27017
      options:
        safe: true
        consistency: :eventual

