common: &common
  title: |
    <p><b>Thanks for checking this functionality.</b></p>
  content: |
  footer: |
    <p>Stay tuned!</p>

create_new_session:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you to run your own sessions online. Choose the topic, the date & time, format (small or large group) and the price. Then market it to your community and make money when users enroll.</p>

schedule_private_session:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and allow you to schedule one-on-one private consultations with existing clients as well as users who come to the site and want to connect with you for specific purposes. You'll set your rate and get paid for your time, if you choose to accept requests. You’ll be in control, time and price-wise.</p>

manage_sessions:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you to run your own sessions online. Choose the topic, the date & time, format (small or large group) and the price. Then market it to your community and earn revenue when users enroll.</p>

testimonials:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you to see and manage testimonials from your community.</p>

community:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you interact and manage your community of followers and friends.</p>
 
feedback:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you to see and manage feedback from your community.</p>

statistics:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and enable you to see relevant statistics about your activity on the platform.</p>

calendar:
  <<: *common
  content: |
    <p>It’ll be released in early 2014 and let you track dates for upcoming online engagements on Prodygia. The more active you are, the more this feature will come in handy and help you organize your time.</p>
