db.shops.remove({name:"商铺"})
db.shops.remove({name:"平价超市"})
db.shops.remove({name:"杂货店"})
db.shops.remove({name:"五金店"})
db.shops.remove({name:"服装店"})
db.shops.remove({name:"士多店"})
db.shops.remove({name:"日杂店"})
db.shops.remove({name:"服饰店"})
db.shops.remove({name:"书店"})
db.shops.remove({name:"鞋店"})
db.shops.remove({name:"烟酒副食店"})
db.shops.remove({name:"小吃店"})
db.shops.remove({name:"茶室"})
db.shops.remove({name:"烟酒茶"})
db.shops.remove({name:"检票处"})
db.shops.remove({name:"商店"})
db.shops.remove({name:"主食店"})
db.shops.remove({name:"提示牌"})
db.shops.remove({name:"衣橱"})
db.shops.remove({name:"修车亭"})
db.shops.remove({name:"栗子王"})
db.shops.remove({name:"棋牌室"})
db.shops.remove({name:"烤串"})
db.shops.remove({name:"鞋柜"})
db.shops.remove({name:"食品店"})
db.shops.remove({name:"食堂"})
db.shops.remove({name:"火锅"})
db.shops.remove({name:/停车场$/})
db.shops.remove({name:/批发$/})
db.shops.remove({type:/^金融/,name:/支行/})
db.shops.remove({type:/^金融/,name:/分理/})
db.shops.remove({name:/创业投资/})
db.shops.remove({name:/卫生站$/})
db.shops.remove({name:/村委会/})
db.shops.remove({name:/[0-9]+号楼$/})
db.shops.remove({name:/[a-zA-Z]+座$/})
db.shops.remove({name:/[0-9]+号$/})
db.shops.remove({name:/[0-9]+号[甲乙丙丁]+$/})
db.shops.remove({name:/[0-9]+幢$/})
db.shops.count({city:"010",name:/路[0-9]+号/})


db.shops.remove({name:/代购店/})
db.shops.remove({name:/代购点/})
db.shops.remove({name:/票/})
db.shops.remove({name:/厕/})
db.shops.remove({name:"住宅"})
db.shops.remove({name:/可以/})
db.shops.remove({"name" : "味道越来越不如以前"})
db.shops.remove({"name" : "感觉量越来越少了"})

db.shops.remove({name:/生殖健康中心$/})
db.shops.remove({type:"生活服务",name:/医院$/})
db.shops.remove({type:"生活服务",name:/口腔$/})